name: Terraform linting and testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - uses: hashicorp/setup-terraform@v3
      name: Setup Terraform
      with:
        terraform_version: "1.9.5"

    - run: terraform fmt -check -recursive
      name: Terraform Format
      id: fmt

    - run: terraform init -backend=false
      name: Terraform Init

    - run: terraform validate
      name: Terraform Validate

    - uses: actions/cache@v2
      name: Cache tflint plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1.1.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --call-module-type=all -f compact

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Run Tests
      run: terraform test